# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV["LC_ALL"] = "en_US.UTF-8"

# DELETE OR ADD FURTHER ENTRIES DOWN BELOW
# AND CHANGE IPs & HOSTNAMES, IF NEEDED
boxes = [
    {
        :name => "federer",
        :cpus => "1",
        :memory => "2048",
        :address => "192.168.56.11"
    },
    {
        :name => "nadal",
        :cpus => "1",
        :memory => "2048",
        :address => "192.168.56.12"
    },
    {
        :name => "djokovic",
        :cpus => "1",
        :memory => "2048",
        :address => "192.168.56.13"
    },
    {
        :name => "murray",
        :cpus => "1",
        :memory => "2048",
        :address => "192.168.56.14"
    }
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/alpine316"
  config.vbguest.auto_update = false
  config.ssh.forward_agent = true
  boxes.each do |vars|
    config.vm.define vars[:name] do |machine|
      machine.vm.hostname = vars[:name]
      machine.vm.provider :virtualbox do |vb|
        vb.name = vars[:name]
        vb.customize ["modifyvm", :id, "--memory", vars[:memory]]
        vb.customize ["modifyvm", :id, "--cpus", vars[:cpus]]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      machine.vm.network :private_network, ip: vars[:address]
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "file", source: "./certificates/ansible_ssh.pub", destination: "~/ansible_ssh.pub"
      machine.vm.provision "shell", path: "./bin/install-certificate.sh"
      machine.vm.provision "shell", path: "./bin/packages-apk.sh"
    end
  end
end
